# Configure the login method (default: sqlite)
# Available options: mongodb, sqlite, mysql, authme, authme-mysql
# We recommend using an AuthMe method if you use AuthMe Reloaded, else SQLite.
# If you have a MongoDB or MySQL/MariaDB database, consider the other methods as well.
login-method: sqlite

# MongoDB configuration (ONLY NEEDED WHEN USING MongoDB LOGIN METHOD)
mongodb:
  # Connection URL
  connection-url: ""

# SQLite configuration (ONLY NEEDED WHEN USING SQLite LOGIN METHOD)
sqlite:
  # Connection URL ({df} is replaced with the plugin data folder)
  connection-url: "jdbc:sqlite:{df}/sqlite.db"
  # Username (leave as-is)
  username: ""
  # Password (leave as-is)
  password: ""

# MySQL configuration (ONLY NEEDED WHEN USING MySQL LOGIN METHOD)
mysql:
  # Connection URL
  connection-url: ""
  # Username
  username: ""
  # Password
  password: ""

# Path to Node.js.
nodejs:
  # Location of Node.js on Linux (it is assumed it is in PATH, modify if needed) (also used for macOS, modify)
  linux: "/usr/bin/env node"
  # Location of Node.js on Windows (it is assumed it is in PATH, modify if needed)
  windows: "nodejs.exe"
