name: "ReConsole"
version: "1.0.0-alpha.2"
description: "A plugin to manage your Minecraft server together with a frontend."
authors: ["Ibrahim Ansari <ansari.ibrahim1@gmail.com>", "Banica Mihai"]
main: "com.reconsole.reconsole.Main"
api-version: 1.12.2

# Setting up commands here.
commands:
  reconsole:
    description: "Used to manage the ReConsole server."
    usage: "/reconsole (register/changepw) <username> <password> <confirmPass> or /reconsole delete <username>"
    permission: ReConsole.use
    permission-message: "ยง4You do not have adequate permission to use this command!"

# Setting up permissions here.
permissions:
  ReConsole.use:
    description: "Allows using the ReConsole dashboard and command."
    default: op

